name: ScarletUI NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.0" # Use Node.js version 16 or later

      # - name: Enable Corepack
      #   run: corepack enable

      - name: Install Specific Yarn Version
        run: npm install -g yarn@4.0.2

      - name: Install Dependencies
        run: yarn install --ignore-path

      - name: List directory contents
        run: ls -l

      - name: Display yarn.lock file
        run: cat yarn.lock

      - name: Build
        run: yarn build

      - name: Bump version and push tag
        run: |
          git config --global user.name 'pixalynx'
          yarn version --patch --message "Bump version to %s [skip ci]"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACESS_TOKEN }}
