name: ScarletUI NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.0" # Use Node.js version 16 or later

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: List directory contents
        run: ls -l

      - name: Display yarn.lock file
        run: cat yarn.lock

      - name: Build
        run: yarn build

      - name: Bump version and push tag
        run: |
          git config --global user.name 'pixalynx'
          # Queue a version change (modify package.json directly or use a yarn version command)
          # Example: Increment patch version manually in package.json
          node -e "let pkg=require('./package.json'); let [major, minor, patch] = pkg.version.split('.').map(Number); pkg.version = `${major}.${minor}.${patch + 1}`; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          # Apply the version change
          yarn version apply --all
          # Commit and tag the change
          git add package.json
          git commit -m "Bump version [skip ci]"
          git tag v$(node -p "require('./package.json').version")
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACESS_TOKEN }}
