name: ScarletUI NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.0" # Use Node.js version 16 or later
          registry-url: "https://registry.npmjs.org"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: List directory contents
        run: ls -l

      - name: Display yarn.lock file
        run: cat yarn.lock

      - name: Build
        run: yarn build

      # - name: Bump version and push tag
      #   run: |
      #     git config --global user.name 'pixalynx'
      #     # Use npm version to bump the version (you can specify "patch", "minor", or "major")
      #     npm version patch
      #     # Commit and tag the change
      #     git push --follow-tags
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACESS_TOKEN }}
