name: ScarletUI NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Bump version and push tag
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          npm version patch -m "Bump version to %s [skip ci]"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_ACESS_TOKEN }}
